/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AddLabelToVcInfoDto } from '../models';
import { CreateVcInfoDto } from '../models';
import { GenerateVpDto } from '../models';
import { IssueVcInfoDto } from '../models';
import { UpdateVcInfoDto } from '../models';
import { VcInfoResponseDto } from '../models';
import { VcInfosResponseDto } from '../models';
/**
 * VcInfosApi - axios parameter creator
 * @export
 */
export const VcInfosApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * リクエストパラメータのidで指定された単一のVC情報に対して、任意の管理用ラベルを追加します。
         * @summary VC情報へのラベル追加
         * @param {AddLabelToVcInfoDto} body 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vcInfosControllerAddLabel: async (body: AddLabelToVcInfoDto, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling vcInfosControllerAddLabel.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling vcInfosControllerAddLabel.');
            }
            const localVarPath = `/api/v1/vc-infos/{id}/label`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * VC情報の所有者、関係者などの管理者としてクライアントアカウントを紐付けます。
         * @summary VC情報へのクライアントアカウント紐付け
         * @param {UpdateVcInfoDto} body 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vcInfosControllerConnectUser: async (body: UpdateVcInfoDto, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling vcInfosControllerConnectUser.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling vcInfosControllerConnectUser.');
            }
            const localVarPath = `/api/v1/vc-infos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 新規VCを発行します。
         * @summary 新規VC発行
         * @param {CreateVcInfoDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vcInfosControllerCreate: async (body: CreateVcInfoDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling vcInfosControllerCreate.');
            }
            const localVarPath = `/api/v1/vc-infos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * VC情報に紐付いたクライアントアカウントの紐付けを解除します。
         * @summary VC情報のクライアントアカウント紐付け解除
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vcInfosControllerDisconnectUser: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling vcInfosControllerDisconnectUser.');
            }
            const localVarPath = `/api/v1/vc-infos/{id}/user`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * アプリケーションが管理するVC情報を一覧として値を返します。
         * @summary VC情報一覧取得
         * @param {number} [page] (必須) ページネーションを表示する際のページ数に当たるクエリパラメーター。全件取得する際は1を指定。(デフォルト: 1)
         * @param {number} [limit] (必須) ページネーションを表示する際のページ数あたりに表示する件数を指定するクエリパラメーター。全件取得する際は0を指定。(デフォルト: 10)
         * @param {string} [label] (任意) 例: \&quot;vc-for-project1\&quot;
         * @param {string} [description] (任意) 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vcInfosControllerFindAll: async (page?: number, limit?: number, label?: string, description?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/vc-infos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (label !== undefined) {
                localVarQueryParameter['label'] = label;
            }

            if (description !== undefined) {
                localVarQueryParameter['description'] = description;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * リクエストパラメータのidで指定された単一のVC情報の詳細情報の値を返します。
         * @summary VC情報詳細取得
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vcInfosControllerFindOne: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling vcInfosControllerFindOne.');
            }
            const localVarPath = `/api/v1/vc-infos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * リクエストパラメータのidで指定されたVC情報から新規VPを発行します。
         * @summary 新規VP情報生成
         * @param {GenerateVpDto} body 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vcInfosControllerGenerateVp: async (body: GenerateVpDto, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling vcInfosControllerGenerateVp.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling vcInfosControllerGenerateVp.');
            }
            const localVarPath = `/api/v1/vc-infos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * VCスキーマを指定せず直接新規VCを発行します。
         * @summary 新規VC発行(スキーマなし)
         * @param {IssueVcInfoDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vcInfosControllerIssue: async (body: IssueVcInfoDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling vcInfosControllerIssue.');
            }
            const localVarPath = `/api/v1/vc-infos/issue`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 外部で発行された既存VCをアップロードし、本アプリケーションに保存します。。
         * @summary 新規VCアップロード
         * @param {any} credentialObject 
         * @param {string} label 
         * @param {string} description 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vcInfosControllerUploadForm: async (credentialObject: any, label: string, description: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'credentialObject' is not null or undefined
            if (credentialObject === null || credentialObject === undefined) {
                throw new RequiredError('credentialObject','Required parameter credentialObject was null or undefined when calling vcInfosControllerUploadForm.');
            }
            // verify required parameter 'label' is not null or undefined
            if (label === null || label === undefined) {
                throw new RequiredError('label','Required parameter label was null or undefined when calling vcInfosControllerUploadForm.');
            }
            // verify required parameter 'description' is not null or undefined
            if (description === null || description === undefined) {
                throw new RequiredError('description','Required parameter description was null or undefined when calling vcInfosControllerUploadForm.');
            }
            const localVarPath = `/api/v1/vc-infos/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


            if (credentialObject !== undefined) { 
                localVarFormParams.append('credentialObject', credentialObject as any);
            }

            if (label !== undefined) { 
                localVarFormParams.append('label', label as any);
            }

            if (description !== undefined) { 
                localVarFormParams.append('description', description as any);
            }

            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VcInfosApi - functional programming interface
 * @export
 */
export const VcInfosApiFp = function(configuration?: Configuration) {
    return {
        /**
         * リクエストパラメータのidで指定された単一のVC情報に対して、任意の管理用ラベルを追加します。
         * @summary VC情報へのラベル追加
         * @param {AddLabelToVcInfoDto} body 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vcInfosControllerAddLabel(body: AddLabelToVcInfoDto, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<VcInfoResponseDto>>> {
            const localVarAxiosArgs = await VcInfosApiAxiosParamCreator(configuration).vcInfosControllerAddLabel(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * VC情報の所有者、関係者などの管理者としてクライアントアカウントを紐付けます。
         * @summary VC情報へのクライアントアカウント紐付け
         * @param {UpdateVcInfoDto} body 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vcInfosControllerConnectUser(body: UpdateVcInfoDto, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await VcInfosApiAxiosParamCreator(configuration).vcInfosControllerConnectUser(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 新規VCを発行します。
         * @summary 新規VC発行
         * @param {CreateVcInfoDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vcInfosControllerCreate(body: CreateVcInfoDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<VcInfoResponseDto>>> {
            const localVarAxiosArgs = await VcInfosApiAxiosParamCreator(configuration).vcInfosControllerCreate(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * VC情報に紐付いたクライアントアカウントの紐付けを解除します。
         * @summary VC情報のクライアントアカウント紐付け解除
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vcInfosControllerDisconnectUser(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await VcInfosApiAxiosParamCreator(configuration).vcInfosControllerDisconnectUser(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * アプリケーションが管理するVC情報を一覧として値を返します。
         * @summary VC情報一覧取得
         * @param {number} [page] (必須) ページネーションを表示する際のページ数に当たるクエリパラメーター。全件取得する際は1を指定。(デフォルト: 1)
         * @param {number} [limit] (必須) ページネーションを表示する際のページ数あたりに表示する件数を指定するクエリパラメーター。全件取得する際は0を指定。(デフォルト: 10)
         * @param {string} [label] (任意) 例: \&quot;vc-for-project1\&quot;
         * @param {string} [description] (任意) 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vcInfosControllerFindAll(page?: number, limit?: number, label?: string, description?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<VcInfosResponseDto>>> {
            const localVarAxiosArgs = await VcInfosApiAxiosParamCreator(configuration).vcInfosControllerFindAll(page, limit, label, description, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * リクエストパラメータのidで指定された単一のVC情報の詳細情報の値を返します。
         * @summary VC情報詳細取得
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vcInfosControllerFindOne(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<VcInfoResponseDto>>> {
            const localVarAxiosArgs = await VcInfosApiAxiosParamCreator(configuration).vcInfosControllerFindOne(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * リクエストパラメータのidで指定されたVC情報から新規VPを発行します。
         * @summary 新規VP情報生成
         * @param {GenerateVpDto} body 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vcInfosControllerGenerateVp(body: GenerateVpDto, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<VcInfoResponseDto>>> {
            const localVarAxiosArgs = await VcInfosApiAxiosParamCreator(configuration).vcInfosControllerGenerateVp(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * VCスキーマを指定せず直接新規VCを発行します。
         * @summary 新規VC発行(スキーマなし)
         * @param {IssueVcInfoDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vcInfosControllerIssue(body: IssueVcInfoDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<VcInfoResponseDto>>> {
            const localVarAxiosArgs = await VcInfosApiAxiosParamCreator(configuration).vcInfosControllerIssue(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 外部で発行された既存VCをアップロードし、本アプリケーションに保存します。。
         * @summary 新規VCアップロード
         * @param {any} credentialObject 
         * @param {string} label 
         * @param {string} description 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vcInfosControllerUploadForm(credentialObject: any, label: string, description: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<VcInfoResponseDto>>> {
            const localVarAxiosArgs = await VcInfosApiAxiosParamCreator(configuration).vcInfosControllerUploadForm(credentialObject, label, description, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * VcInfosApi - factory interface
 * @export
 */
export const VcInfosApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * リクエストパラメータのidで指定された単一のVC情報に対して、任意の管理用ラベルを追加します。
         * @summary VC情報へのラベル追加
         * @param {AddLabelToVcInfoDto} body 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vcInfosControllerAddLabel(body: AddLabelToVcInfoDto, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<VcInfoResponseDto>> {
            return VcInfosApiFp(configuration).vcInfosControllerAddLabel(body, id, options).then((request) => request(axios, basePath));
        },
        /**
         * VC情報の所有者、関係者などの管理者としてクライアントアカウントを紐付けます。
         * @summary VC情報へのクライアントアカウント紐付け
         * @param {UpdateVcInfoDto} body 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vcInfosControllerConnectUser(body: UpdateVcInfoDto, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return VcInfosApiFp(configuration).vcInfosControllerConnectUser(body, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 新規VCを発行します。
         * @summary 新規VC発行
         * @param {CreateVcInfoDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vcInfosControllerCreate(body: CreateVcInfoDto, options?: AxiosRequestConfig): Promise<AxiosResponse<VcInfoResponseDto>> {
            return VcInfosApiFp(configuration).vcInfosControllerCreate(body, options).then((request) => request(axios, basePath));
        },
        /**
         * VC情報に紐付いたクライアントアカウントの紐付けを解除します。
         * @summary VC情報のクライアントアカウント紐付け解除
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vcInfosControllerDisconnectUser(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return VcInfosApiFp(configuration).vcInfosControllerDisconnectUser(id, options).then((request) => request(axios, basePath));
        },
        /**
         * アプリケーションが管理するVC情報を一覧として値を返します。
         * @summary VC情報一覧取得
         * @param {number} [page] (必須) ページネーションを表示する際のページ数に当たるクエリパラメーター。全件取得する際は1を指定。(デフォルト: 1)
         * @param {number} [limit] (必須) ページネーションを表示する際のページ数あたりに表示する件数を指定するクエリパラメーター。全件取得する際は0を指定。(デフォルト: 10)
         * @param {string} [label] (任意) 例: \&quot;vc-for-project1\&quot;
         * @param {string} [description] (任意) 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vcInfosControllerFindAll(page?: number, limit?: number, label?: string, description?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<VcInfosResponseDto>> {
            return VcInfosApiFp(configuration).vcInfosControllerFindAll(page, limit, label, description, options).then((request) => request(axios, basePath));
        },
        /**
         * リクエストパラメータのidで指定された単一のVC情報の詳細情報の値を返します。
         * @summary VC情報詳細取得
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vcInfosControllerFindOne(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<VcInfoResponseDto>> {
            return VcInfosApiFp(configuration).vcInfosControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * リクエストパラメータのidで指定されたVC情報から新規VPを発行します。
         * @summary 新規VP情報生成
         * @param {GenerateVpDto} body 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vcInfosControllerGenerateVp(body: GenerateVpDto, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<VcInfoResponseDto>> {
            return VcInfosApiFp(configuration).vcInfosControllerGenerateVp(body, id, options).then((request) => request(axios, basePath));
        },
        /**
         * VCスキーマを指定せず直接新規VCを発行します。
         * @summary 新規VC発行(スキーマなし)
         * @param {IssueVcInfoDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vcInfosControllerIssue(body: IssueVcInfoDto, options?: AxiosRequestConfig): Promise<AxiosResponse<VcInfoResponseDto>> {
            return VcInfosApiFp(configuration).vcInfosControllerIssue(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 外部で発行された既存VCをアップロードし、本アプリケーションに保存します。。
         * @summary 新規VCアップロード
         * @param {any} credentialObject 
         * @param {string} label 
         * @param {string} description 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vcInfosControllerUploadForm(credentialObject: any, label: string, description: string, options?: AxiosRequestConfig): Promise<AxiosResponse<VcInfoResponseDto>> {
            return VcInfosApiFp(configuration).vcInfosControllerUploadForm(credentialObject, label, description, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VcInfosApi - object-oriented interface
 * @export
 * @class VcInfosApi
 * @extends {BaseAPI}
 */
export class VcInfosApi extends BaseAPI {
    /**
     * リクエストパラメータのidで指定された単一のVC情報に対して、任意の管理用ラベルを追加します。
     * @summary VC情報へのラベル追加
     * @param {AddLabelToVcInfoDto} body 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VcInfosApi
     */
    public async vcInfosControllerAddLabel(body: AddLabelToVcInfoDto, id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<VcInfoResponseDto>> {
        return VcInfosApiFp(this.configuration).vcInfosControllerAddLabel(body, id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * VC情報の所有者、関係者などの管理者としてクライアントアカウントを紐付けます。
     * @summary VC情報へのクライアントアカウント紐付け
     * @param {UpdateVcInfoDto} body 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VcInfosApi
     */
    public async vcInfosControllerConnectUser(body: UpdateVcInfoDto, id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return VcInfosApiFp(this.configuration).vcInfosControllerConnectUser(body, id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 新規VCを発行します。
     * @summary 新規VC発行
     * @param {CreateVcInfoDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VcInfosApi
     */
    public async vcInfosControllerCreate(body: CreateVcInfoDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<VcInfoResponseDto>> {
        return VcInfosApiFp(this.configuration).vcInfosControllerCreate(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * VC情報に紐付いたクライアントアカウントの紐付けを解除します。
     * @summary VC情報のクライアントアカウント紐付け解除
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VcInfosApi
     */
    public async vcInfosControllerDisconnectUser(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return VcInfosApiFp(this.configuration).vcInfosControllerDisconnectUser(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * アプリケーションが管理するVC情報を一覧として値を返します。
     * @summary VC情報一覧取得
     * @param {number} [page] (必須) ページネーションを表示する際のページ数に当たるクエリパラメーター。全件取得する際は1を指定。(デフォルト: 1)
     * @param {number} [limit] (必須) ページネーションを表示する際のページ数あたりに表示する件数を指定するクエリパラメーター。全件取得する際は0を指定。(デフォルト: 10)
     * @param {string} [label] (任意) 例: \&quot;vc-for-project1\&quot;
     * @param {string} [description] (任意) 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VcInfosApi
     */
    public async vcInfosControllerFindAll(page?: number, limit?: number, label?: string, description?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<VcInfosResponseDto>> {
        return VcInfosApiFp(this.configuration).vcInfosControllerFindAll(page, limit, label, description, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * リクエストパラメータのidで指定された単一のVC情報の詳細情報の値を返します。
     * @summary VC情報詳細取得
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VcInfosApi
     */
    public async vcInfosControllerFindOne(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<VcInfoResponseDto>> {
        return VcInfosApiFp(this.configuration).vcInfosControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * リクエストパラメータのidで指定されたVC情報から新規VPを発行します。
     * @summary 新規VP情報生成
     * @param {GenerateVpDto} body 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VcInfosApi
     */
    public async vcInfosControllerGenerateVp(body: GenerateVpDto, id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<VcInfoResponseDto>> {
        return VcInfosApiFp(this.configuration).vcInfosControllerGenerateVp(body, id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * VCスキーマを指定せず直接新規VCを発行します。
     * @summary 新規VC発行(スキーマなし)
     * @param {IssueVcInfoDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VcInfosApi
     */
    public async vcInfosControllerIssue(body: IssueVcInfoDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<VcInfoResponseDto>> {
        return VcInfosApiFp(this.configuration).vcInfosControllerIssue(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 外部で発行された既存VCをアップロードし、本アプリケーションに保存します。。
     * @summary 新規VCアップロード
     * @param {any} credentialObject 
     * @param {string} label 
     * @param {string} description 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VcInfosApi
     */
    public async vcInfosControllerUploadForm(credentialObject: any, label: string, description: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<VcInfoResponseDto>> {
        return VcInfosApiFp(this.configuration).vcInfosControllerUploadForm(credentialObject, label, description, options).then((request) => request(this.axios, this.basePath));
    }
}
