/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AddLabelToVpInfoDto } from '../models';
import { CreateVpInfoDto } from '../models';
import { UpdateVcInfoDto } from '../models';
import { VpInfoDetailDto } from '../models';
import { VpInfoResponseDto } from '../models';
/**
 * VpInfosApi - axios parameter creator
 * @export
 */
export const VpInfosApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * リクエストパラメータのidで指定された単一のVP情報に対して、任意の管理用ラベルを追加します。
         * @summary VP情報へのラベル追加
         * @param {AddLabelToVpInfoDto} body 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vpInfosControllerAddLabel: async (body: AddLabelToVpInfoDto, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling vpInfosControllerAddLabel.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling vpInfosControllerAddLabel.');
            }
            const localVarPath = `/api/v1/vp-infos/{id}/label`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * VP情報の所有者、関係者などの管理者としてクライアントアカウントを紐付けます。
         * @summary VP情報へのクライアントアカウント紐付け
         * @param {UpdateVcInfoDto} body 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vpInfosControllerConnectUser: async (body: UpdateVcInfoDto, id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling vpInfosControllerConnectUser.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling vpInfosControllerConnectUser.');
            }
            const localVarPath = `/api/v1/vp-infos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 新規VPを生成します。
         * @summary 新規VP生成
         * @param {CreateVpInfoDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vpInfosControllerCreate: async (body: CreateVpInfoDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling vpInfosControllerCreate.');
            }
            const localVarPath = `/api/v1/vp-infos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * VP情報に紐付いたクライアントアカウントの紐付けを解除します。
         * @summary VP情報のクライアントアカウント紐付け解除
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vpInfosControllerDisconnectUser: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling vpInfosControllerDisconnectUser.');
            }
            const localVarPath = `/api/v1/vp-infos/{id}/user`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * アプリケーションが管理するVP情報を一覧として値を返します。
         * @summary VP情報一覧取得
         * @param {number} [page] (必須) ページネーションを表示する際のページ数に当たるクエリパラメーター。全件取得する際は1を指定。(デフォルト: 1)
         * @param {number} [limit] (必須) ページネーションを表示する際のページ数あたりに表示する件数を指定するクエリパラメーター。全件取得する際は0を指定。(デフォルト: 10)
         * @param {string} [label] (任意) 例: \&quot;vc-for-project1\&quot;
         * @param {string} [description] (任意) 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vpInfosControllerFindAll: async (page?: number, limit?: number, label?: string, description?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/vp-infos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (label !== undefined) {
                localVarQueryParameter['label'] = label;
            }

            if (description !== undefined) {
                localVarQueryParameter['description'] = description;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * リクエストパラメータのidで指定された単一のVP情報の詳細情報の値を返します。
         * @summary VP情報詳細取得
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vpInfosControllerFindOne: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling vpInfosControllerFindOne.');
            }
            const localVarPath = `/api/v1/vp-infos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 外部で発行された既存VPをアップロードし、本アプリケーションに保存します。。
         * @summary 新規VPアップロード
         * @param {any} credentialObject 
         * @param {string} label 
         * @param {string} description 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        vpInfosControllerUploadForm: async (credentialObject: any, label: string, description: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'credentialObject' is not null or undefined
            if (credentialObject === null || credentialObject === undefined) {
                throw new RequiredError('credentialObject','Required parameter credentialObject was null or undefined when calling vpInfosControllerUploadForm.');
            }
            // verify required parameter 'label' is not null or undefined
            if (label === null || label === undefined) {
                throw new RequiredError('label','Required parameter label was null or undefined when calling vpInfosControllerUploadForm.');
            }
            // verify required parameter 'description' is not null or undefined
            if (description === null || description === undefined) {
                throw new RequiredError('description','Required parameter description was null or undefined when calling vpInfosControllerUploadForm.');
            }
            const localVarPath = `/api/v1/vp-infos/upload`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


            if (credentialObject !== undefined) { 
                localVarFormParams.append('credentialObject', credentialObject as any);
            }

            if (label !== undefined) { 
                localVarFormParams.append('label', label as any);
            }

            if (description !== undefined) { 
                localVarFormParams.append('description', description as any);
            }

            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * VpInfosApi - functional programming interface
 * @export
 */
export const VpInfosApiFp = function(configuration?: Configuration) {
    return {
        /**
         * リクエストパラメータのidで指定された単一のVP情報に対して、任意の管理用ラベルを追加します。
         * @summary VP情報へのラベル追加
         * @param {AddLabelToVpInfoDto} body 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vpInfosControllerAddLabel(body: AddLabelToVpInfoDto, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<VpInfoResponseDto>>> {
            const localVarAxiosArgs = await VpInfosApiAxiosParamCreator(configuration).vpInfosControllerAddLabel(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * VP情報の所有者、関係者などの管理者としてクライアントアカウントを紐付けます。
         * @summary VP情報へのクライアントアカウント紐付け
         * @param {UpdateVcInfoDto} body 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vpInfosControllerConnectUser(body: UpdateVcInfoDto, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await VpInfosApiAxiosParamCreator(configuration).vpInfosControllerConnectUser(body, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 新規VPを生成します。
         * @summary 新規VP生成
         * @param {CreateVpInfoDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vpInfosControllerCreate(body: CreateVpInfoDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await VpInfosApiAxiosParamCreator(configuration).vpInfosControllerCreate(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * VP情報に紐付いたクライアントアカウントの紐付けを解除します。
         * @summary VP情報のクライアントアカウント紐付け解除
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vpInfosControllerDisconnectUser(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await VpInfosApiAxiosParamCreator(configuration).vpInfosControllerDisconnectUser(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * アプリケーションが管理するVP情報を一覧として値を返します。
         * @summary VP情報一覧取得
         * @param {number} [page] (必須) ページネーションを表示する際のページ数に当たるクエリパラメーター。全件取得する際は1を指定。(デフォルト: 1)
         * @param {number} [limit] (必須) ページネーションを表示する際のページ数あたりに表示する件数を指定するクエリパラメーター。全件取得する際は0を指定。(デフォルト: 10)
         * @param {string} [label] (任意) 例: \&quot;vc-for-project1\&quot;
         * @param {string} [description] (任意) 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vpInfosControllerFindAll(page?: number, limit?: number, label?: string, description?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<VpInfoResponseDto>>> {
            const localVarAxiosArgs = await VpInfosApiAxiosParamCreator(configuration).vpInfosControllerFindAll(page, limit, label, description, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * リクエストパラメータのidで指定された単一のVP情報の詳細情報の値を返します。
         * @summary VP情報詳細取得
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vpInfosControllerFindOne(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<VpInfoDetailDto>>> {
            const localVarAxiosArgs = await VpInfosApiAxiosParamCreator(configuration).vpInfosControllerFindOne(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 外部で発行された既存VPをアップロードし、本アプリケーションに保存します。。
         * @summary 新規VPアップロード
         * @param {any} credentialObject 
         * @param {string} label 
         * @param {string} description 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vpInfosControllerUploadForm(credentialObject: any, label: string, description: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<VpInfoResponseDto>>> {
            const localVarAxiosArgs = await VpInfosApiAxiosParamCreator(configuration).vpInfosControllerUploadForm(credentialObject, label, description, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * VpInfosApi - factory interface
 * @export
 */
export const VpInfosApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * リクエストパラメータのidで指定された単一のVP情報に対して、任意の管理用ラベルを追加します。
         * @summary VP情報へのラベル追加
         * @param {AddLabelToVpInfoDto} body 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vpInfosControllerAddLabel(body: AddLabelToVpInfoDto, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<VpInfoResponseDto>> {
            return VpInfosApiFp(configuration).vpInfosControllerAddLabel(body, id, options).then((request) => request(axios, basePath));
        },
        /**
         * VP情報の所有者、関係者などの管理者としてクライアントアカウントを紐付けます。
         * @summary VP情報へのクライアントアカウント紐付け
         * @param {UpdateVcInfoDto} body 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vpInfosControllerConnectUser(body: UpdateVcInfoDto, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return VpInfosApiFp(configuration).vpInfosControllerConnectUser(body, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 新規VPを生成します。
         * @summary 新規VP生成
         * @param {CreateVpInfoDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vpInfosControllerCreate(body: CreateVpInfoDto, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return VpInfosApiFp(configuration).vpInfosControllerCreate(body, options).then((request) => request(axios, basePath));
        },
        /**
         * VP情報に紐付いたクライアントアカウントの紐付けを解除します。
         * @summary VP情報のクライアントアカウント紐付け解除
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vpInfosControllerDisconnectUser(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return VpInfosApiFp(configuration).vpInfosControllerDisconnectUser(id, options).then((request) => request(axios, basePath));
        },
        /**
         * アプリケーションが管理するVP情報を一覧として値を返します。
         * @summary VP情報一覧取得
         * @param {number} [page] (必須) ページネーションを表示する際のページ数に当たるクエリパラメーター。全件取得する際は1を指定。(デフォルト: 1)
         * @param {number} [limit] (必須) ページネーションを表示する際のページ数あたりに表示する件数を指定するクエリパラメーター。全件取得する際は0を指定。(デフォルト: 10)
         * @param {string} [label] (任意) 例: \&quot;vc-for-project1\&quot;
         * @param {string} [description] (任意) 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vpInfosControllerFindAll(page?: number, limit?: number, label?: string, description?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<VpInfoResponseDto>> {
            return VpInfosApiFp(configuration).vpInfosControllerFindAll(page, limit, label, description, options).then((request) => request(axios, basePath));
        },
        /**
         * リクエストパラメータのidで指定された単一のVP情報の詳細情報の値を返します。
         * @summary VP情報詳細取得
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vpInfosControllerFindOne(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<VpInfoDetailDto>> {
            return VpInfosApiFp(configuration).vpInfosControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 外部で発行された既存VPをアップロードし、本アプリケーションに保存します。。
         * @summary 新規VPアップロード
         * @param {any} credentialObject 
         * @param {string} label 
         * @param {string} description 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async vpInfosControllerUploadForm(credentialObject: any, label: string, description: string, options?: AxiosRequestConfig): Promise<AxiosResponse<VpInfoResponseDto>> {
            return VpInfosApiFp(configuration).vpInfosControllerUploadForm(credentialObject, label, description, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * VpInfosApi - object-oriented interface
 * @export
 * @class VpInfosApi
 * @extends {BaseAPI}
 */
export class VpInfosApi extends BaseAPI {
    /**
     * リクエストパラメータのidで指定された単一のVP情報に対して、任意の管理用ラベルを追加します。
     * @summary VP情報へのラベル追加
     * @param {AddLabelToVpInfoDto} body 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VpInfosApi
     */
    public async vpInfosControllerAddLabel(body: AddLabelToVpInfoDto, id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<VpInfoResponseDto>> {
        return VpInfosApiFp(this.configuration).vpInfosControllerAddLabel(body, id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * VP情報の所有者、関係者などの管理者としてクライアントアカウントを紐付けます。
     * @summary VP情報へのクライアントアカウント紐付け
     * @param {UpdateVcInfoDto} body 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VpInfosApi
     */
    public async vpInfosControllerConnectUser(body: UpdateVcInfoDto, id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return VpInfosApiFp(this.configuration).vpInfosControllerConnectUser(body, id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 新規VPを生成します。
     * @summary 新規VP生成
     * @param {CreateVpInfoDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VpInfosApi
     */
    public async vpInfosControllerCreate(body: CreateVpInfoDto, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return VpInfosApiFp(this.configuration).vpInfosControllerCreate(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * VP情報に紐付いたクライアントアカウントの紐付けを解除します。
     * @summary VP情報のクライアントアカウント紐付け解除
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VpInfosApi
     */
    public async vpInfosControllerDisconnectUser(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return VpInfosApiFp(this.configuration).vpInfosControllerDisconnectUser(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * アプリケーションが管理するVP情報を一覧として値を返します。
     * @summary VP情報一覧取得
     * @param {number} [page] (必須) ページネーションを表示する際のページ数に当たるクエリパラメーター。全件取得する際は1を指定。(デフォルト: 1)
     * @param {number} [limit] (必須) ページネーションを表示する際のページ数あたりに表示する件数を指定するクエリパラメーター。全件取得する際は0を指定。(デフォルト: 10)
     * @param {string} [label] (任意) 例: \&quot;vc-for-project1\&quot;
     * @param {string} [description] (任意) 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VpInfosApi
     */
    public async vpInfosControllerFindAll(page?: number, limit?: number, label?: string, description?: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<VpInfoResponseDto>> {
        return VpInfosApiFp(this.configuration).vpInfosControllerFindAll(page, limit, label, description, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * リクエストパラメータのidで指定された単一のVP情報の詳細情報の値を返します。
     * @summary VP情報詳細取得
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VpInfosApi
     */
    public async vpInfosControllerFindOne(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<VpInfoDetailDto>> {
        return VpInfosApiFp(this.configuration).vpInfosControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 外部で発行された既存VPをアップロードし、本アプリケーションに保存します。。
     * @summary 新規VPアップロード
     * @param {any} credentialObject 
     * @param {string} label 
     * @param {string} description 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof VpInfosApi
     */
    public async vpInfosControllerUploadForm(credentialObject: any, label: string, description: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<VpInfoResponseDto>> {
        return VpInfosApiFp(this.configuration).vpInfosControllerUploadForm(credentialObject, label, description, options).then((request) => request(this.axios, this.basePath));
    }
}
