/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { VcInfo } from './vc-info';
import { VcSchema } from './vc-schema';
 /**
 * 
 *
 * @export
 * @interface BadgeResponseDto
 */
export interface BadgeResponseDto {

    /**
     * バッジの識別子
     *
     * @type {string}
     * @memberof BadgeResponseDto
     * @example 3bfc3721-eb7c-4a5b-b5ac-94d1f158911f
     */
    id: string;

    /**
     * バッジのラベル名
     *
     * @type {string}
     * @memberof BadgeResponseDto
     * @example sample-badge-1
     */
    label: string;

    /**
     * バッジのファイル名
     *
     * @type {string}
     * @memberof BadgeResponseDto
     * @example badge-12345-12345.png
     */
    filename: string;

    /**
     * バッジの作成目的や用途など任意で設定可能な説明文
     *
     * @type {string}
     * @memberof BadgeResponseDto
     * @example This is Group A for Project X.
     */
    description: string;

    /**
     * バッジの状態(1: 利用可, 0: 利用停止中)
     *
     * @type {number}
     * @memberof BadgeResponseDto
     * @example 1
     */
    status: number;

    /**
     * バッジに紐付いたVCスキーマの配列
     *
     * @type {VcSchema}
     * @memberof BadgeResponseDto
     * @example {"id":"fc765af3-63da-4030-9c2d-3c6b44ae283d","title":"hogeVC","version":"1.0.0","vcInfos":[{"id":"41e840da-ec7a-4c9b-8783-9b4160719bea","label":"cdsd","hash":"QmSfRENacd2K2kbjYzPSxRKThZpYio4yX1Xb9MMnSxxZKu","createdAt":"2024-10-18T04:18:18.191Z","updatedAt":"2024-10-18T04:18:18.191Z"}],"vcSchemaProperties":[{"id":"98164eb2-6650-4198-813a-cc9e11c221dd","propIndex":2,"propName":"age","propType":"number","createdAt":"2024-10-18T04:17:56.585Z","updatedAt":"2024-10-18T04:17:56.585Z"},{"id":"866154a6-e0ba-4caa-aaec-4d923f55cb4a","propIndex":1,"propName":"name","propType":"string","createdAt":"2024-10-18T04:17:56.584Z","updatedAt":"2024-10-18T04:17:56.584Z"}],"groups":[{"id":"123e4567-e89b-12d3-a456-426614174000","name":"Project Group 1","status":"active","description":"This is Project Group 1.","createdAt":"2024-05-24T06:39:54.352Z","updatedAt":"2024-05-24T06:39:54.352Z"}],"createdAt":"2024-10-18T04:17:56.564Z","updatedAt":"2024-10-18T04:17:56.564Z"}
     */
    vcSchema: VcSchema;

    /**
     * バッジに紐付いたVC情報の配列
     *
     * @type {VcInfo}
     * @memberof BadgeResponseDto
     * @example {"id":"dcb884cb-bf93-437d-906b-67fb893dea98","hash":"Qma1dK93xnJpyuSeQcFiq6JC5LANRTBegE3EUN79udbCcv","description":"","createdAt":"2024-07-09T04:37:14.248Z","updatedAt":"2024-07-09T04:37:14.248Z"}
     */
    vcInfo: VcInfo;

    /**
     * バッジの作成日時
     *
     * @type {string}
     * @memberof BadgeResponseDto
     * @example 2024-05-24T06:39:54.352Z
     */
    createdAt: string;

    /**
     * バッジの最終更新日時
     *
     * @type {string}
     * @memberof BadgeResponseDto
     * @example 2024-05-24T06:39:54.352Z
     */
    updatedAt: string;
}
