/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { VcInfo } from './vc-info';
import { VcSchema } from './vc-schema';
 /**
 * 
 *
 * @export
 * @interface Badge
 */
export interface Badge {

    /**
     * (必須) バッジの識別子
     *
     * @type {string}
     * @memberof Badge
     * @example 123e4567-e89b-12d3-a456-426614174000
     */
    id: string;

    /**
     * (任意) バッジのラベル名
     *
     * @type {string}
     * @memberof Badge
     * @example sample-badge-1
     */
    label?: string;

    /**
     * (任意) バッジのファイル名
     *
     * @type {string}
     * @memberof Badge
     * @example badge-12345-12345.png
     */
    filename?: string;

    /**
     * (任意) バッジの作成目的や用途など任意で設定可能な説明文
     *
     * @type {string}
     * @memberof Badge
     * @example This is Sample Badge 1.
     */
    description: string;

    /**
     * (必須) バッジの状態(1: アクティブ, 0: 停止中)
     *
     * @type {number}
     * @memberof Badge
     * @example 1
     */
    status: number;

    /**
     * (任意) バッジに紐付いたVCスキーマ
     *
     * @type {VcSchema}
     * @memberof Badge
     */
    vcSchema?: VcSchema;

    /**
     * (任意) バッジに紐付き、メタデータとなるVC情報
     *
     * @type {VcInfo}
     * @memberof Badge
     */
    vcInfo?: VcInfo;

    /**
     * (必須) グループの作成日時
     *
     * @type {string}
     * @memberof Badge
     * @example 2024-05-24T06:39:25.756Z
     */
    createdAt: string;

    /**
     * (必須) グループの最終更新日時
     *
     * @type {string}
     * @memberof Badge
     * @example 2024-05-24T06:39:25.756Z
     */
    updatedAt: string;
}
