/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { VcSchemaProperty } from './vc-schema-property';
 /**
 * 
 *
 * @export
 * @interface CreateVcSchemaDto
 */
export interface CreateVcSchemaDto {

    /**
     * (必須) 新規生成するVCスキーマのタイトル
     *
     * @type {string}
     * @memberof CreateVcSchemaDto
     * @example VC Schema sample
     */
    title: string;

    /**
     * (必須) VCスキーマのバージョン(デフォルト: 1.0.0)
     *
     * @type {string}
     * @memberof CreateVcSchemaDto
     * @example 1.0.0
     */
    version: string;

    /**
     * (任意) VCスキーマに設定する@context文字列の配列
     *
     * @type {Array<string>}
     * @memberof CreateVcSchemaDto
     * @example ["https://www.w3.org/ns/credentials/v2","https://purl.imsglobal.org/spec/ob/v3p0/context-3.0.3.json","https://purl.imsglobal.org/spec/ob/v3p0/extensions.json"]
     */
    contexts?: Array<string>;

    /**
     * (任意) VCスキーマの説明文
     *
     * @type {string}
     * @memberof CreateVcSchemaDto
     * @example This is the description of did
     */
    description?: string;

    /**
     * (任意) このスキーマがバッジのスキーマか否か(デフォルト: false)
     *
     * @type {boolean}
     * @memberof CreateVcSchemaDto
     * @example false
     */
    isBadgeSchema: boolean;

    /**
     * (任意) バッジの画像のファイル識別子。'`isBadgeSchema`プロパティが`true`であり、バッジスキーマとして利用する場合は必須のパラメータ。
     *
     * @type {string}
     * @memberof CreateVcSchemaDto
     * @example 3bfc3721-eb7c-4a5b-b5ac-94d1f158911f
     */
    fileId: string;

    /**
     * (必須) VCのスキーマの各項目における項目名と項目型のオブジェクトの配列
     *
     * @type {Array<VcSchemaProperty>}
     * @memberof CreateVcSchemaDto
     * @example [{"propIndex":1,"propName":"id","propType":"string"},{"propIndex":2,"propName":"status","propType":"object"},{"propIndex":3,"propName":"age","propType":"number","parentObjectIndex":2},{"propIndex":4,"propName":"isActive","propType":"boolean","parentObjectIndex":2},{"propIndex":5,"propName":"hogeArray","propType":"array:string"}]
     */
    propArray: Array<VcSchemaProperty>;
}
