/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateVpInfoDto
 */
export interface CreateVpInfoDto {

    /**
     * (必須) VPを生成する元となるVC情報の識別子の配列
     *
     * @type {Array<string>}
     * @memberof CreateVpInfoDto
     * @example ["3bfc3721-eb7c-4a5b-b5ac-94d1f158911f"]
     */
    vcInfoIds: Array<string>;

    /**
     * (必須) VP生成時の署名に用いるDID情報の識別子
     *
     * @type {string}
     * @memberof CreateVpInfoDto
     * @example 3bfc3721-eb7c-4a5b-b5ac-94d1f158911f
     */
    didInfoId: string;

    /**
     * (任意) VPの識別や整理などの管理するにあったてメタデータとして任意で設定可能な単語のフレーズ。(例: vc-for-project1)
     *
     * @type {string}
     * @memberof CreateVpInfoDto
     * @example vp-for-project1
     */
    label?: string;

    /**
     * (任意) VPの生成目的や用途などを任意で設定可能な説明文
     *
     * @type {string}
     * @memberof CreateVpInfoDto
     * @example This is the description of did
     */
    description?: string;
}
