/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Group } from './group';
import { User } from './user';
import { VpInfo } from './vp-info';
 /**
 * 
 *
 * @export
 * @interface DidInfo
 */
export interface DidInfo {

    /**
     * (必須) DID情報の識別子
     *
     * @type {string}
     * @memberof DidInfo
     * @example 123e4567-e89b-12d3-a456-426614174000
     */
    id: string;

    /**
     * (必須) DID情報の管理に用いるユニークな識別子
     *
     * @type {string}
     * @memberof DidInfo
     * @example 32bad62a-4186-4d04-a26a-fcee79d5824b
     */
    manageUuid: string;

    /**
     * (必須) DID
     *
     * @type {string}
     * @memberof DidInfo
     * @example did:key:12345
     */
    did: string;

    /**
     * (必須) DIDメソッド
     *
     * @type {string}
     * @memberof DidInfo
     * @example key
     */
    method: DidInfoMethodEnum;

    /**
     * (任意) DIDの識別や整理などの管理するにあったてメタデータとして任意で設定可能な単語のフレーズ。(例: did-for-project1)
     *
     * @type {string}
     * @memberof DidInfo
     * @example did-info-1
     */
    label: string;

    /**
     * (任意) did:webメソッドでDIDを生成する際に必要なドメイン名。DIDによって指定されたドメインがドメインネームシステム(DNS)を通じて解決されるときのホスト名。did:webメソッド以外では必要のないカラムである。
     *
     * @type {string}
     * @memberof DidInfo
     * @example domain-name.com
     */
    domainName: string;

    /**
     * (必須) DID情報に紐付いた秘密鍵を本アプリケーションで保管しているか否か
     *
     * @type {boolean}
     * @memberof DidInfo
     * @example true
     */
    existPrivateKey: boolean;

    /**
     * (任意) DID情報の生成目的や用途など任意で設定可能な説明文
     *
     * @type {string}
     * @memberof DidInfo
     * @example This is Project Group 1.
     */
    description: string;

    /**
     * (任意) DID情報に紐付いたアカウントの配列
     *
     * @type {User}
     * @memberof DidInfo
     */
    user?: User;

    /**
     * (任意) DIDを生成したユーザーアカウント
     *
     * @type {User}
     * @memberof DidInfo
     */
    createdBy: User;

    /**
     * (任意) 生成時に署名にDIDを用いたVP情報
     *
     * @type {VpInfo}
     * @memberof DidInfo
     */
    vpInfos?: VpInfo;

    /**
     * (任意) DID情報に紐づいたグループの配列
     *
     * @type {Array<Group>}
     * @memberof DidInfo
     */
    groups?: Array<Group>;

    /**
     * (必須) DID情報の作成日時
     *
     * @type {string}
     * @memberof DidInfo
     * @example 2024-05-24T06:39:25.756Z
     */
    createdAt: string;

    /**
     * (必須) DID情報の最終更新
     *
     * @type {string}
     * @memberof DidInfo
     * @example 2024-05-24T06:39:25.756Z
     */
    updatedAt: string;
}

/**
 * @export
 * @enum {string}
 */
export enum DidInfoMethodEnum {
    Key = 'key',
    Web = 'web',
    Ethr = 'ethr',
    Ethrarbitrumgoerli = 'ethr:arbitrum:goerli',
    Ethrsepolia = 'ethr:sepolia'
}

