/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DidInfo } from './did-info';
 /**
 * 
 *
 * @export
 * @interface DidInfoResponseDto
 */
export interface DidInfoResponseDto {

    /**
     * @type {DidInfo}
     * @memberof DidInfoResponseDto
     * @example {"id":"bde07fae-69de-44c4-bb87-1763c2058b56","manageUuid":"32bad62a-4186-4d04-a26a-fcee79d5824b","did":"did:key:z6MkhGeGj7u5htkCYjE4PaQ8HUqjYyTmxpDb6Q1MqUpUDsN7","method":"key","label":"did-for-project1","domainName":"","existPrivateKey":true,"description":"This is the description of did","createdAt":"2024-10-17T03:32:38.901Z","updatedAt":"2024-10-17T03:32:38.901Z"}
     */
    didInfo: DidInfo;

    /**
     * @type {any}
     * @memberof DidInfoResponseDto
     * @example {"id":"did:ethr:0x030a48b2e2c4890ff2c26b91b93f8f899191c21bd6d52722e62a5251c55dfa22a5","verificationMethod":[{"id":"did:ethr:0x030a48b2e2c4890ff2c26b91b93f8f899191c21bd6d52722e62a5251c55dfa22a5#controller","type":"EcdsaSecp256k1RecoveryMethod2020","controller":"did:ethr:0x030a48b2e2c4890ff2c26b91b93f8f899191c21bd6d52722e62a5251c55dfa22a5","blockchainAccountId":"eip155:1:0x28DA61f78488BFa22acFcB25675af265835e8aF8"},{"id":"did:ethr:0x030a48b2e2c4890ff2c26b91b93f8f899191c21bd6d52722e62a5251c55dfa22a5#controllerKey","type":"EcdsaSecp256k1VerificationKey2019","controller":"did:ethr:0x030a48b2e2c4890ff2c26b91b93f8f899191c21bd6d52722e62a5251c55dfa22a5","publicKeyHex":"030a48b2e2c4890ff2c26b91b93f8f899191c21bd6d52722e62a5251c55dfa22a5"}],"authentication":["did:ethr:0x030a48b2e2c4890ff2c26b91b93f8f899191c21bd6d52722e62a5251c55dfa22a5#controller","did:ethr:0x030a48b2e2c4890ff2c26b91b93f8f899191c21bd6d52722e62a5251c55dfa22a5#controllerKey"],"assertionMethod":["did:ethr:0x030a48b2e2c4890ff2c26b91b93f8f899191c21bd6d52722e62a5251c55dfa22a5#controller","did:ethr:0x030a48b2e2c4890ff2c26b91b93f8f899191c21bd6d52722e62a5251c55dfa22a5#controllerKey"],"@context":["https://www.w3.org/ns/did/v1","https://w3id.org/security/suites/secp256k1recovery-2020/v2","https://w3id.org/security/v3-unstable"]}
     */
    didObject: any;
}
