/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface FileResponseDto
 */
export interface FileResponseDto {

    /**
     * (必須) ファイルの識別子
     *
     * @type {string}
     * @memberof FileResponseDto
     * @example 3bfc3721-eb7c-4a5b-b5ac-94d1f158911f
     */
    id: string;

    /**
     * (必須) システム内で管理される際にシステムによって名付けられるユニークなファイル名
     *
     * @type {string}
     * @memberof FileResponseDto
     * @example sample_file
     */
    filename: string;

    /**
     * (必須) システム内で管理される際にシステムによって名付けられるユニークなファイル名
     *
     * @type {string}
     * @memberof FileResponseDto
     * @example sample_file
     */
    originalname: string;

    /**
     * (必須) システムへアップロード時の元のファイル名
     *
     * @type {string}
     * @memberof FileResponseDto
     * @example text/csv:nfhorif2Efr2
     */
    fileData: string;

    /**
     * (必須) ファイル形式
     *
     * @type {string}
     * @memberof FileResponseDto
     * @example text/csv
     */
    fileType: string;

    /**
     * (必須) ファイル形式
     *
     * @type {string}
     * @memberof FileResponseDto
     * @example image/png
     */
    type: string;

    /**
     * (任意) ファイルがCSVの場合、アカウントデータ生成実行に使用されたか。(true: 実行済み, false: 未使用)
     *
     * @type {boolean}
     * @memberof FileResponseDto
     * @example false
     */
    executed: boolean;

    /**
     * (必須) ファイルのステータス
     *
     * @type {number}
     * @memberof FileResponseDto
     * @example 0
     */
    status: number;

    /**
     * ファイルをアップロードしたユーザーアカウント
     *
     * @type {User}
     * @memberof FileResponseDto
     * @example {"id":"e8973f1a-a80f-4243-8061-144565b640f2","name":"admin","email":"admin@email.com","needActivateFlow":false,"status":"active","role":"admin","createdAt":"2025-02-04T22:32:21.343Z","updatedAt":"2025-02-04T22:32:21.343Z"}
     */
    createdBy: User;

    /**
     * (必須) ファイルの作成日時
     *
     * @type {string}
     * @memberof FileResponseDto
     * @example 2024-05-24T06:39:54.352Z
     */
    createdAt: string;

    /**
     * (必須) グループの最終更新日時
     *
     * @type {string}
     * @memberof FileResponseDto
     * @example 2024-05-24T06:39:54.352Z
     */
    updatedAt: string;
}
