/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetProfileResponseDto
 */
export interface GetProfileResponseDto {

    /**
     * アカウントの識別子
     *
     * @type {string}
     * @memberof GetProfileResponseDto
     * @example 70ceb004-0550-460a-ad40-c31614bb0109
     */
    userId: string;

    /**
     * アカウントの名前
     *
     * @type {string}
     * @memberof GetProfileResponseDto
     * @example clinet1
     */
    name: string;

    /**
     * アカウントのメールアドレス
     *
     * @type {string}
     * @memberof GetProfileResponseDto
     * @example client1@email.com
     */
    email: string;

    /**
     * アカウントロール(\"admin\", \"user\", \"client\")
     *
     * @type {string}
     * @memberof GetProfileResponseDto
     * @example client
     */
    role: GetProfileResponseDtoRoleEnum;

    /**
     * JWTが発行された日時
     *
     * @type {number}
     * @memberof GetProfileResponseDto
     * @example 1737255455
     */
    iat: number;

    /**
     * JWTが失効する日時
     *
     * @type {number}
     * @memberof GetProfileResponseDto
     * @example 1737269855
     */
    exp: number;
}

/**
 * @export
 * @enum {string}
 */
export enum GetProfileResponseDtoRoleEnum {
    Admin = 'admin',
    User = 'user',
    Client = 'client'
}

