/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface IssueVcInfoDto
 */
export interface IssueVcInfoDto {

    /**
     * (必須) VCの発行者の識別子として用いる文字列の値。現在はDIDのみがサポートされていますが、今後のアップデートでDID以外の文字列をサポートする予定です。
     *
     * @type {string}
     * @memberof IssueVcInfoDto
     * @example did:key:z6MkepWVAjYFGvTdffTcJJcE1sJKLHuCefxqw72dPodoxJrP
     */
    issuer: string;

    /**
     * (必須) VCの主張内容(クレーム)となる値のオブジェクト型の値
     *
     * @type {any}
     * @memberof IssueVcInfoDto
     * @example {"age":20,"name":"test"}
     */
    credentialSubject: any;

    /**
     * (任意) VCの識別や整理などの管理するにあったてメタデータとして任意で設定可能な単語のフレーズ。(例: vc-for-project1)
     *
     * @type {string}
     * @memberof IssueVcInfoDto
     * @example vc-for-project1
     */
    label?: string;

    /**
     * (任意) VCの発行目的や用途など任意で設定可能な説明文
     *
     * @type {string}
     * @memberof IssueVcInfoDto
     * @example This is the description of VC
     */
    description?: string;
}
