/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Group } from './group';
import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface Mail
 */
export interface Mail {

    /**
     * (必須) 送信済みメールの識別子
     *
     * @type {string}
     * @memberof Mail
     * @example 123e4567-e89b-12d3-a456-426614174000
     */
    id: string;

    /**
     * (必須) 送信済みメールの件名
     *
     * @type {string}
     * @memberof Mail
     * @example [iDroit Dashboard] mail title
     */
    title: string;

    /**
     * (必須) 送信済みメールの内容
     *
     * @type {string}
     * @memberof Mail
     * @example This is Mail content.
     */
    content: string;

    /**
     * (必須) 全てのuser権限アカウントに対して送信するか。(true: 全てのuser権限アカウントに送信, false: 全てのuser権限アカウントに送信しない)
     *
     * @type {boolean}
     * @memberof Mail
     * @example false
     */
    forEveryUser: boolean;

    /**
     * (必須) 全てのclient権限アカウントに対して送信するか。(true: 全てのclient権限アカウントに送信, false: 全てのclient権限アカウントに送信しない)
     *
     * @type {boolean}
     * @memberof Mail
     * @example false
     */
    forEveryClient: boolean;

    /**
     * (任意) メールの送信先となるユーザーアカウントの配列
     *
     * @type {Array<User>}
     * @memberof Mail
     */
    users?: Array<User>;

    /**
     * (任意) メールの送信先となるグループの配列
     *
     * @type {Array<Group>}
     * @memberof Mail
     */
    groups?: Array<Group>;

    /**
     * (必須) メール送信操作を行ったAdmin権限アカウント
     *
     * @type {Array<User>}
     * @memberof Mail
     */
    createdBy?: Array<User>;

    /**
     * (必須) メールの送信日時
     *
     * @type {string}
     * @memberof Mail
     * @example 2024-05-24T06:39:25.756Z
     */
    createdAt: string;

    /**
     * (必須) メールの送信日時
     *
     * @type {string}
     * @memberof Mail
     * @example 2024-05-24T06:39:25.756Z
     */
    updatedAt: string;
}
