/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Group } from './group';
import { User } from './user';
import { VcSchema } from './vc-schema';
 /**
 * 
 *
 * @export
 * @interface ModelFile
 */
export interface ModelFile {

    /**
     * (必須) ファイルの識別子
     *
     * @type {string}
     * @memberof ModelFile
     * @example 123e4567-e89b-12d3-a456-426614174000
     */
    id: string;

    /**
     * (任意) システム内で管理される際にシステムによって名付けられるユニークなファイル名
     *
     * @type {string}
     * @memberof ModelFile
     * @example file-1729389547388-110834208.csv
     */
    filename: string;

    /**
     * (必須) システムへアップロード時の元のファイル名
     *
     * @type {string}
     * @memberof ModelFile
     * @example testdata.csv
     */
    originalname: string;

    /**
     * (必須) ファイル形式
     *
     * @type {string}
     * @memberof ModelFile
     * @example text/csv
     */
    type: string;

    /**
     * (必須) ファイルのバイナリデータ
     *
     * @type {string}
     * @memberof ModelFile
     * @example text/csv
     */
    fileData: string;

    /**
     * (任意) ファイルがCSVの場合、アカウントデータ生成実行に使用されたか。(true: 実行済み, false: 未使用)
     *
     * @type {boolean}
     * @memberof ModelFile
     * @example false
     */
    executed: boolean;

    /**
     * (必須) ファイルのステータス
     *
     * @type {number}
     * @memberof ModelFile
     * @example 0
     */
    status: number;

    /**
     * (任意) ファイルを紐づけたグループの配列
     *
     * @type {Array<Group>}
     * @memberof ModelFile
     */
    group: Array<Group>;

    /**
     * (任意) ファイルに紐づいたVCスキーマ
     *
     * @type {VcSchema}
     * @memberof ModelFile
     */
    vcSchema?: VcSchema;

    /**
     * (必須) ファイルをアップロードしたユーザーアカウント。
     *
     * @type {User}
     * @memberof ModelFile
     */
    createdBy: User;

    /**
     * (必須) ファイルの作成日時
     *
     * @type {string}
     * @memberof ModelFile
     * @example 2024-05-24T06:39:25.756Z
     */
    createdAt: string;

    /**
     * (必須) グループの最終更新日時
     *
     * @type {string}
     * @memberof ModelFile
     * @example 2024-05-24T06:39:25.756Z
     */
    updatedAt: string;
}
