/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ResolveDidResponseDto
 */
export interface ResolveDidResponseDto {

    /**
     * @type {Array<string>}
     * @memberof ResolveDidResponseDto
     * @example ["https://www.w3.org/ns/did/v1","https://w3id.org/security/suites/ed25519-2018/v1","https://w3id.org/security/suites/x25519-2019/v1"]
     */
    context: Array<string>;

    /**
     * @type {string}
     * @memberof ResolveDidResponseDto
     * @example did:key:z6MkepWVAjYFGvTdffTcJJcE1sJKLHuCefxqw72dPodoxJrP
     */
    id: string;

    /**
     * @type {Array<any>}
     * @memberof ResolveDidResponseDto
     * @example [{"id":"did:key:z6MkepWVAjYFGvTdffTcJJcE1sJKLHuCefxqw72dPodoxJrP#z6MkepWVAjYFGvTdffTcJJcE1sJKLHuCefxqw72dPodoxJrP","type":"Ed25519VerificationKey2018","controller":"did:key:z6MkepWVAjYFGvTdffTcJJcE1sJKLHuCefxqw72dPodoxJrP","publicKeyBase58":"NFSaVHowNyAZAcucjePAmkKWidMEniVF67hZXfo3651"},{"id":"did:key:z6MkepWVAjYFGvTdffTcJJcE1sJKLHuCefxqw72dPodoxJrP#z6LShmgtsCTMEhTZ9gKNkCrcW754zWswWSB5FwdF1KiCSwSt","type":"X25519KeyAgreementKey2019","controller":"did:key:z6MkepWVAjYFGvTdffTcJJcE1sJKLHuCefxqw72dPodoxJrP","publicKeyBase58":"76WjLteV9Ejp4HwcDZLfBWrb9NLpopzvNxuZWs4fjZg8"}]
     */
    verificationMethod: Array<any>;

    /**
     * @type {Array<string>}
     * @memberof ResolveDidResponseDto
     * @example ["did:key:z6MkepWVAjYFGvTdffTcJJcE1sJKLHuCefxqw72dPodoxJrP#z6MkepWVAjYFGvTdffTcJJcE1sJKLHuCefxqw72dPodoxJrP"]
     */
    assertionMethod: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof ResolveDidResponseDto
     * @example ["did:key:z6MkepWVAjYFGvTdffTcJJcE1sJKLHuCefxqw72dPodoxJrP#z6MkepWVAjYFGvTdffTcJJcE1sJKLHuCefxqw72dPodoxJrP"]
     */
    authentication: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof ResolveDidResponseDto
     * @example ["did:key:z6MkepWVAjYFGvTdffTcJJcE1sJKLHuCefxqw72dPodoxJrP#z6MkepWVAjYFGvTdffTcJJcE1sJKLHuCefxqw72dPodoxJrP"]
     */
    capabilityInvocation: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof ResolveDidResponseDto
     * @example ["did:key:z6MkepWVAjYFGvTdffTcJJcE1sJKLHuCefxqw72dPodoxJrP#z6MkepWVAjYFGvTdffTcJJcE1sJKLHuCefxqw72dPodoxJrP"]
     */
    capabilityDelegation: Array<string>;

    /**
     * @type {Array<string>}
     * @memberof ResolveDidResponseDto
     * @example ["did:key:z6MkepWVAjYFGvTdffTcJJcE1sJKLHuCefxqw72dPodoxJrP#z6LShmgtsCTMEhTZ9gKNkCrcW754zWswWSB5FwdF1KiCSwSt"]
     */
    keyAgreement: Array<string>;
}
