/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SendMailBatchDto
 */
export interface SendMailBatchDto {

    /**
     * (必須) メールの件名
     *
     * @type {string}
     * @memberof SendMailBatchDto
     * @example [iDroit Dashboard] News
     */
    title: string;

    /**
     * (必須) 全てのクライアントアカウントに対して送信するか (true: 全てのクライアントアカウントに送信, false: 全てのクライアントアカウントに送信しない)
     *
     * @type {boolean}
     * @memberof SendMailBatchDto
     * @example false
     */
    forEveryClient: boolean;

    /**
     * (必須) 全てのユーザーアカウントに対して送信するか (true: 全てのユーザーアカウントに送信, false: 全てのユーザーアカウントに送信しない)
     *
     * @type {boolean}
     * @memberof SendMailBatchDto
     * @example false
     */
    forEveryUser: boolean;

    /**
     * (任意) メールの送信対象のユーザーアカウント識別子の配列
     *
     * @type {Array<string>}
     * @memberof SendMailBatchDto
     * @example ["3bfc3721-eb7c-4a5b-b5ac-94d1f158911f"]
     */
    userIds?: Array<string>;

    /**
     * (任意) 送信対象のグループ識別子の配列。グループを指定した場合グループに紐付くユーザーアカウントとクライアントアカウント全てにメールが送信される
     *
     * @type {Array<string>}
     * @memberof SendMailBatchDto
     * @example ["3bfc3721-eb7c-4a5b-b5ac-94d1f158911f"]
     */
    groupIds?: Array<string>;

    /**
     * (必須) メールの内容
     *
     * @type {string}
     * @memberof SendMailBatchDto
     * @example This is the mail content.
     */
    content: string;
}
