/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UpdateVcSchemaDto
 */
export interface UpdateVcSchemaDto {

    /**
     * (必須) VCスキーマを紐づけるグループ識別子の配列。
     *
     * @type {Array<string>}
     * @memberof UpdateVcSchemaDto
     * @example ["3bfc3721-eb7c-4a5b-b5ac-94d1f158911f"]
     */
    groupIds?: Array<string>;

    /**
     * (必須) VCスキーマを紐づけるcontext項目の配列。
     *
     * @type {Array<string>}
     * @memberof UpdateVcSchemaDto
     * @example ["https://www.w3.org/ns/credentials/v2","https://purl.imsglobal.org/spec/ob/v3p0/context-3.0.3.json","https://purl.imsglobal.org/spec/ob/v3p0/extensions.json"]
     */
    contexts?: Array<string>;
}
