/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DidInfo } from './did-info';
import { Group } from './group';
import { Mail } from './mail';
import { User } from './user';
import { UserToken } from './user-token';
import { VcInfo } from './vc-info';
import { VcSchema } from './vc-schema';
import { Verification } from './verification';
import { VpInfo } from './vp-info';
 /**
 * 
 *
 * @export
 * @interface UserResponseDto
 */
export interface UserResponseDto {

    /**
     * ユーザーアカウントの識別子
     *
     * @type {string}
     * @memberof UserResponseDto
     * @example 3bfc3721-eb7c-4a5b-b5ac-94d1f158911f
     */
    id: string;

    /**
     * ユーザーアカウントの名前
     *
     * @type {string}
     * @memberof UserResponseDto
     * @example John Doe
     */
    name: string;

    /**
     * ユーザーアカウントのメールアドレス
     *
     * @type {string}
     * @memberof UserResponseDto
     * @example user1@email.com
     */
    email: string;

    /**
     * ユーザーアクティベーション(true: アクティブ /false: 停止中)
     *
     * @type {boolean}
     * @memberof UserResponseDto
     * @example true
     */
    needActivateFlow: boolean;

    /**
     * ユーザーのアカウントステータス(\"inactive\": アクティブ未完了, \"acrivating\": アクティブ作業途中, \"active\": アクティブ中, \"deactive\": 論理削除済)
     *
     * @type {string}
     * @memberof UserResponseDto
     * @example active
     */
    status: UserResponseDtoStatusEnum;

    /**
     * ユーザーのアカウントロール(\"admin\", \"user\", \"client\")
     *
     * @type {string}
     * @memberof UserResponseDto
     * @example user
     */
    role: UserResponseDtoRoleEnum;

    /**
     * (任意) ユーザーアカウントがアップロードしたファイルの配列。
     *
     * @type {Array<UserToken>}
     * @memberof UserResponseDto
     */
    userTokens: Array<UserToken>;

    /**
     * ユーザーアカウントを作成したユーザーアカウント
     *
     * @type {User}
     * @memberof UserResponseDto
     * @example {"id":"e8973f1a-a80f-4243-8061-144565b640f2","name":"admin","email":"admin@email.com","needActivateFlow":false,"status":"active","role":"admin","createdAt":"2025-02-04T22:32:21.343Z","updatedAt":"2025-02-04T22:32:21.343Z"}
     */
    createdBy: User;

    /**
     * ユーザーアカウントに紐付けられたDID情報の配列
     *
     * @type {Array<DidInfo>}
     * @memberof UserResponseDto
     * @example [{"id":"bde07fae-69de-44c4-bb87-1763c2058b56","manageUuid":"32bad62a-4186-4d04-a26a-fcee79d5824b","did":"did:key:z6MkhGeGj7u5htkCYjE4PaQ8HUqjYyTmxpDb6Q1MqUpUDsN7","method":"key","label":"did-for-project1","domainName":"","existPrivateKey":true,"description":"This is the description of did","createdAt":"2024-07-09T04:37:14.248Z","updatedAt":"2024-07-09T04:37:14.248Z"}]
     */
    didInfos?: Array<DidInfo>;

    /**
     * ユーザーアカウントに紐付けられたVC情報の配列
     *
     * @type {Array<VcInfo>}
     * @memberof UserResponseDto
     * @example [{"id":"123e4567-e89b-12d3-a456-426614174000","label":"vc-info-1","hash":"11bf5b37-e0b8-42e0-8dcf-dc8c4aefc000","description":"","createdAt":"2024-07-09T04:37:14.248Z","updatedAt":"2024-07-09T04:37:14.248Z"}]
     */
    vcInfos?: Array<VcInfo>;

    /**
     * ユーザーアカウントに紐付けられたVP情報の配列
     *
     * @type {Array<VpInfo>}
     * @memberof UserResponseDto
     * @example [{"id":"dcb884cb-bf93-437d-906b-67fb893dea98","hash":"Qma1dK93xnJpyuSeQcFiq6JC5LANRTBegE3EUN79udbCcv","description":"","createdAt":"2024-05-24T06:39:54.352Z","updatedAt":"2024-05-24T06:39:54.352Z"}]
     */
    vpInfos?: Array<VpInfo>;

    /**
     * ユーザーアカウントが作成したグループの配列
     *
     * @type {Array<Group>}
     * @memberof UserResponseDto
     * @example [{"id":"123e4567-e89b-12d3-a456-426614174000","name":"Project Group 1","status":"active","description":"This is Project Group 1.","createdAt":"2024-05-24T06:39:54.352Z","updatedAt":"2024-05-24T06:39:54.352Z"}]
     */
    groups?: Array<Group>;

    /**
     * ユーザーアカウントに紐付けされたVP情報の配列
     *
     * @type {Array<User>}
     * @memberof UserResponseDto
     * @example [{"id":"dcb884cb-bf93-437d-906b-67fb893dea98","hash":"Qma1dK93xnJpyuSeQcFiq6JC5LANRTBegE3EUN79udbCcv","description":"","createdAt":"2024-05-24T06:39:54.352Z","updatedAt":"2024-05-24T06:39:54.352Z"}]
     */
    createdUsers?: Array<User>;

    /**
     * ユーザーが作成したVC情報の配列
     *
     * @type {Array<VcInfo>}
     * @memberof UserResponseDto
     * @example [{"id":"dcb884cb-bf93-437d-906b-67fb893dea98","hash":"Qma1dK93xnJpyuSeQcFiq6JC5LANRTBegE3EUN79udbCcv","description":"","createdAt":"2024-05-24T06:39:54.352Z","updatedAt":"2024-05-24T06:39:54.352Z"}]
     */
    createdVcInfos?: Array<VcInfo>;

    /**
     * ユーザーが作成したVP情報の配列
     *
     * @type {Array<VpInfo>}
     * @memberof UserResponseDto
     * @example [{"id":"dcb884cb-bf93-437d-906b-67fb893dea98","hash":"Qma1dK93xnJpyuSeQcFiq6JC5LANRTBegE3EUN79udbCcv","description":"","createdAt":"2024-05-24T06:39:54.352Z","updatedAt":"2024-05-24T06:39:54.352Z"}]
     */
    createdVpInfos?: Array<VpInfo>;

    /**
     * ユーザーアカウントが作成したグループの配列
     *
     * @type {Array<Group>}
     * @memberof UserResponseDto
     * @example [{"id":"123e4567-e89b-12d3-a456-426614174000","name":"Project Group 1","status":"active","description":"This is Project Group 1.","createdAt":"2024-05-24T06:39:54.352Z","updatedAt":"2024-05-24T06:39:54.352Z"}]
     */
    createdGroups?: Array<Group>;

    /**
     * ユーザーが作成したDID情報の配列
     *
     * @type {Array<DidInfo>}
     * @memberof UserResponseDto
     * @example [{"id":"bde07fae-69de-44c4-bb87-1763c2058b56","manageUuid":"32bad62a-4186-4d04-a26a-fcee79d5824b","did":"did:key:z6MkhGeGj7u5htkCYjE4PaQ8HUqjYyTmxpDb6Q1MqUpUDsN7","method":"key","label":"did-for-project1","domainName":"","existPrivateKey":true,"description":"This is the description of did","createdAt":"2024-07-09T04:37:14.248Z","updatedAt":"2024-07-09T04:37:14.248Z"}]
     */
    createdDidInfos?: Array<DidInfo>;

    /**
     * ユーザーが作成したVCスキーマの配列
     *
     * @type {Array<VcSchema>}
     * @memberof UserResponseDto
     * @example [{"id":"fc765af3-63da-4030-9c2d-3c6b44ae283d","title":"hogeVC","version":"1.0.0","description":"","createdAt":"2024-10-18T04:17:56.564Z","updatedAt":"2024-10-18T04:17:56.564Z"}]
     */
    createdVcSchemas?: Array<VcSchema>;

    /**
     * ユーザーアカウントが実行した検証結果の配列
     *
     * @type {Array<Verification>}
     * @memberof UserResponseDto
     * @example []
     */
    createdVerifications?: Array<Verification>;

    /**
     * Admin権限アカウントが送信したメールの配列
     *
     * @type {Array<Mail>}
     * @memberof UserResponseDto
     * @example []
     */
    createdMails?: Array<Mail>;

    /**
     * ユーザーアカウントに紐付けされたファイルの配列
     *
     * @type {Array<any>}
     * @memberof UserResponseDto
     * @example []
     */
    createdFiles?: Array<any>;

    /**
     * ユーザーアカウントの作成日時
     *
     * @type {string}
     * @memberof UserResponseDto
     * @example 2024-05-24T06:39:54.352Z
     */
    createdAt: string;

    /**
     * ユーザーアカウントの更新日時
     *
     * @type {string}
     * @memberof UserResponseDto
     * @example 2024-05-24T06:39:54.352Z
     */
    updatedAt: string;
}

/**
 * @export
 * @enum {string}
 */
export enum UserResponseDtoStatusEnum {
    Inactive = 'inactive',
    Activating = 'activating',
    Active = 'active',
    Deactive = 'deactive'
}
/**
 * @export
 * @enum {string}
 */
export enum UserResponseDtoRoleEnum {
    Admin = 'admin',
    User = 'user',
    Client = 'client'
}

