/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Badge } from './badge';
import { Group } from './group';
import { User } from './user';
import { VcSchema } from './vc-schema';
import { Verification } from './verification';
import { VpInfo } from './vp-info';
 /**
 * 
 *
 * @export
 * @interface VcInfo
 */
export interface VcInfo {

    /**
     * (必須) VC情報の識別子
     *
     * @type {string}
     * @memberof VcInfo
     * @example 123e4567-e89b-12d3-a456-426614174000
     */
    id: string;

    /**
     * (任意) VCの識別や整理などの管理するにあったてメタデータとして任意で設定可能な単語のフレーズ。(例: vc-for-project1)
     *
     * @type {string}
     * @memberof VcInfo
     * @example vc-info-1
     */
    label: string;

    /**
     * (必須) VCのハッシュ値。VCの保管における識別子として用いる。
     *
     * @type {string}
     * @memberof VcInfo
     * @example 11bf5b37-e0b8-42e0-8dcf-dc8c4aefc000
     */
    hash: string;

    /**
     * (任意) VCの発行目的や用途など任意で設定可能な説明文。
     *
     * @type {string}
     * @memberof VcInfo
     * @example This is Project Group 1.
     */
    description: string;

    /**
     * (任意) VC情報を生成したユーザーアカウント
     *
     * @type {User}
     * @memberof VcInfo
     */
    createdBy: User;

    /**
     * (任意) 発行したVCの元となるVCスキーマ
     *
     * @type {VcSchema}
     * @memberof VcInfo
     */
    vcSchema?: VcSchema;

    /**
     * (任意) VC情報と紐付いたアカウント
     *
     * @type {User}
     * @memberof VcInfo
     */
    user?: User;

    /**
     * (任意) このVCを元に生成したVP情報の配列
     *
     * @type {Array<VpInfo>}
     * @memberof VcInfo
     */
    vpInfos?: Array<VpInfo>;

    /**
     * (任意) VC情報に紐づいたグループの配列
     *
     * @type {Array<Group>}
     * @memberof VcInfo
     */
    groups?: Array<Group>;

    /**
     * (任意) VC情報と紐付いたバッジ
     *
     * @type {Badge}
     * @memberof VcInfo
     */
    badge?: Badge;

    /**
     * (任意) このVCの検証結果の配列。
     *
     * @type {Array<Verification>}
     * @memberof VcInfo
     */
    verifications?: Array<Verification>;

    /**
     * (必須) VC情報の作成日時
     *
     * @type {string}
     * @memberof VcInfo
     * @example 2024-05-24T06:39:25.756Z
     */
    createdAt: string;

    /**
     * (必須) VC情報の更新日時
     *
     * @type {string}
     * @memberof VcInfo
     * @example 2024-05-24T06:39:25.756Z
     */
    updatedAt: string;
}
