/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { LinkDto } from './link-dto';
import { MetaDto } from './meta-dto';
import { VcSchema } from './vc-schema';
 /**
 * 
 *
 * @export
 * @interface VcSchemasResponseDto
 */
export interface VcSchemasResponseDto {

    /**
     * Array of VC schema items
     *
     * @type {Array<VcSchema>}
     * @memberof VcSchemasResponseDto
     * @example [{"id":"fc765af3-63da-4030-9c2d-3c6b44ae283d","title":"hogeVC","version":"1.0.0","vcInfos":[{"id":"41e840da-ec7a-4c9b-8783-9b4160719bea","label":"cdsd","hash":"QmSfRENacd2K2kbjYzPSxRKThZpYio4yX1Xb9MMnSxxZKu","createdAt":"2024-10-18T04:18:18.191Z","updatedAt":"2024-10-18T04:18:18.191Z"}],"vcSchemaProperties":[{"id":"98164eb2-6650-4198-813a-cc9e11c221dd","propIndex":2,"propName":"age","propType":"number","createdAt":"2024-10-18T04:17:56.585Z","updatedAt":"2024-10-18T04:17:56.585Z"},{"id":"866154a6-e0ba-4caa-aaec-4d923f55cb4a","propIndex":1,"propName":"name","propType":"string","createdAt":"2024-10-18T04:17:56.584Z","updatedAt":"2024-10-18T04:17:56.584Z"}],"groups":[{"id":"123e4567-e89b-12d3-a456-426614174000","name":"Project Group 1","status":"active","description":"This is Project Group 1.","createdAt":"2024-05-24T06:39:54.352Z","updatedAt":"2024-05-24T06:39:54.352Z"}],"createdAt":"2024-10-18T04:17:56.564Z","updatedAt":"2024-10-18T04:17:56.564Z"}]
     */
    items: Array<VcSchema>;

    /**
     * @type {MetaDto}
     * @memberof VcSchemasResponseDto
     */
    meta: MetaDto;

    /**
     * @type {LinkDto}
     * @memberof VcSchemasResponseDto
     */
    links: LinkDto;
}
