/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Badge } from './badge';
import { Group } from './group';
import { User } from './user';
import { VcContext } from './vc-context';
import { VcInfo } from './vc-info';
import { VcSchemaProperty } from './vc-schema-property';
 /**
 * 
 *
 * @export
 * @interface VcSchemaResponseDto
 */
export interface VcSchemaResponseDto {

    /**
     * VCスキーマの識別子
     *
     * @type {string}
     * @memberof VcSchemaResponseDto
     * @example 3bfc3721-eb7c-4a5b-b5ac-94d1f158911f
     */
    id: string;

    /**
     * VCスキーマのタイトル
     *
     * @type {string}
     * @memberof VcSchemaResponseDto
     * @example This is VC Schema sample 1
     */
    title: string;

    /**
     * VCスキーマのバージョン
     *
     * @type {string}
     * @memberof VcSchemaResponseDto
     * @example 1.0.0
     */
    version: string;

    /**
     * VCスキーマの説明文
     *
     * @type {string}
     * @memberof VcSchemaResponseDto
     * @example This is VC Schema 1.
     */
    description: string;

    /**
     * VCスキーマがバッジのスキーマか否か
     *
     * @type {string}
     * @memberof VcSchemaResponseDto
     * @example false
     */
    isBadgeSchema: string;

    /**
     * @type {Array<VcInfo>}
     * @memberof VcSchemaResponseDto
     * @example [{"id":"123e4567-e89b-12d3-a456-426614174000","label":"vc-info-1","hash":"11bf5b37-e0b8-42e0-8dcf-dc8c4aefc000","description":"This is Project Group 1.","createdAt":"2024-05-24T06:39:54.352Z","updatedAt":"2024-05-24T06:39:54.352Z"}]
     */
    vcInfos: Array<VcInfo>;

    /**
     * VCのスキーマのJSONスキーマコンテキスト
     *
     * @type {Array<VcContext>}
     * @memberof VcSchemaResponseDto
     * @example []
     */
    vcContexts: Array<VcContext>;

    /**
     * VCのスキーマの各項目における項目名と項目型のオブジェクトの配列
     *
     * @type {Array<VcSchemaProperty>}
     * @memberof VcSchemaResponseDto
     * @example [{"id":"53d624fb-456b-4500-8673-d53dc672bbeb","propName":"age","propType":"number","createdAt":"2024-07-09T04:25:19.878Z","updatedAt":"2024-07-09T04:25:19.878Z"},{"id":"576a7023-141c-4dea-8d8c-b1162b7f5963","propName":"name","propType":"string","createdAt":"2024-07-09T04:25:19.877Z","updatedAt":"2024-07-09T04:25:19.877Z"}]
     */
    vcSchemaProperties: Array<VcSchemaProperty>;

    /**
     * @type {Array<Group>}
     * @memberof VcSchemaResponseDto
     * @example [{"id":"3bfc3721-eb7c-4a5b-b5ac-94d1f158911f","name":"Group A","description":"This is Group A for Project X.","createdAt":"2024-05-24T07:37:04.273Z","updatedAt":"2024-05-24T07:37:18.000Z"}]
     */
    groups: Array<Group>;

    /**
     * VCスキーマを紐付けたバッジ
     *
     * @type {Array<Badge>}
     * @memberof VcSchemaResponseDto
     */
    badges: Array<Badge>;

    /**
     * VCスキーマに紐付けるバッジ用の画像。`isBadgeSchema`プロパティが`true`の場合必須。
     *
     * @type {any}
     * @memberof VcSchemaResponseDto
     */
    file: any;

    /**
     * VCスキーマを作成したユーザーアカウント
     *
     * @type {User}
     * @memberof VcSchemaResponseDto
     * @example {"id":"e8973f1a-a80f-4243-8061-144565b640f2","name":"admin","email":"admin@email.com","needActivateFlow":false,"status":"active","role":"admin","createdAt":"2025-02-04T22:32:21.343Z","updatedAt":"2025-02-04T22:32:21.343Z"}
     */
    createdBy: User;

    /**
     * VCスキーマの作成日時
     *
     * @type {string}
     * @memberof VcSchemaResponseDto
     * @example 2024-05-24T06:39:54.352Z
     */
    createdAt: string;

    /**
     * VCスキーマの最終更新日時
     *
     * @type {string}
     * @memberof VcSchemaResponseDto
     * @example 2024-05-24T06:39:54.352Z
     */
    updatedAt: string;
}
