/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { User } from './user';
import { VcInfo } from './vc-info';
import { VpInfo } from './vp-info';
 /**
 * 
 *
 * @export
 * @interface VerificationResponseDto
 */
export interface VerificationResponseDto {

    /**
     * 検証結果の識別子
     *
     * @type {string}
     * @memberof VerificationResponseDto
     * @example 3bfc3721-eb7c-4a5b-b5ac-94d1f158911f
     */
    id: string;

    /**
     * 検証結果の識別や整理などの管理するにあったてメタデータとして任意で設定可能な単語のフレーズ。(例: verify-for-check)
     *
     * @type {string}
     * @memberof VerificationResponseDto
     * @example This is the description of VP
     */
    label: string;

    /**
     * (必須) VC/VPの検証結果(true: 検証に成功, false: 検証に失敗)
     *
     * @type {boolean}
     * @memberof VerificationResponseDto
     * @example true
     */
    result: boolean;

    /**
     * グループを作成したユーザーアカウント
     *
     * @type {User}
     * @memberof VerificationResponseDto
     * @example {"id":"e8973f1a-a80f-4243-8061-144565b640f2","name":"admin","email":"admin@email.com","needActivateFlow":false,"status":"active","role":"admin","createdAt":"2025-02-04T22:32:21.343Z","updatedAt":"2025-02-04T22:32:21.343Z"}
     */
    createdBy: User;

    /**
     * 検証を実行したVC情報の識別子
     *
     * @type {VcInfo}
     * @memberof VerificationResponseDto
     * @example {"id":"dcb884cb-bf93-437d-906b-67fb893dea98","title":"schema 1_1720499834247","hash":"Qma1dK93xnJpyuSeQcFiq6JC5LANRTBegE3EUN79udbCcv","description":"","createdAt":"2024-07-09T04:37:14.248Z","updatedAt":"2024-07-09T04:37:14.248Z"}
     */
    vcInfo: VcInfo;

    /**
     * 検証を実行したVP情報の識別子
     *
     * @type {VpInfo}
     * @memberof VerificationResponseDto
     * @example {"id":"dcb884cb-bf93-437d-906b-67fb893dea98","title":"schema 1_1720499834247","hash":"Qma1dK93xnJpyuSeQcFiq6JC5LANRTBegE3EUN79udbCcv","description":"","createdAt":"2024-07-09T04:37:14.248Z","updatedAt":"2024-07-09T04:37:14.248Z"}
     */
    vpInfo: VpInfo;

    /**
     * 検証実行時の日時
     *
     * @type {string}
     * @memberof VerificationResponseDto
     * @example 2024-05-24T06:39:54.352Z
     */
    createdAt: string;

    /**
     * 検証結果の最終更新日
     *
     * @type {string}
     * @memberof VerificationResponseDto
     * @example 2024-05-24T06:39:54.352Z
     */
    updatedAt: string;
}
