/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface VerificationDto
 */
export interface VerificationDto {

    /**
     * (必須) 検証結果の識別や整理などの管理するにあったてメタデータとして任意で設定可能な単語のフレーズ。(例: verify-for-check)
     *
     * @type {string}
     * @memberof VerificationDto
     * @example verify-for-check
     */
    label?: string;

    /**
     * (任意) 検証を実行するVC情報の識別子。VC情報の識別子を指定して検証を実行する場合は必須。
     *
     * @type {string}
     * @memberof VerificationDto
     * @example 3bfc3721-eb7c-4a5b-b5ac-94d1f158911f
     */
    vcInfoId?: string;

    /**
     * (任意) 検証を実行するVP情報の識別子。VP情報の識別子を指定して検証を実行する場合は必須。
     *
     * @type {string}
     * @memberof VerificationDto
     * @example 3bfc3721-eb7c-4a5b-b5ac-94d1f158911f
     */
    vpInfoId?: string;

    /**
     * (任意) 検証を実行するVCのJSONテキストデータ。VCのJSONテキストデータを入力して検証を実行する場合は必須。
     *
     * @type {any}
     * @memberof VerificationDto
     * @example {"credentialSubject":{"age":20,"name":"test"},"issuer":{"id":"did:ethr:0x030a48b2e2c4890ff2c26b91b93f8f899191c21bd6d52722e62a5251c55dfa22a5"},"type":["VerifiableCredential"],"@context":["https://www.w3.org/2018/credentials/v1"],"issuanceDate":"2024-07-09T04:37:14.000Z","proof":{"type":"JwtProof2020","jwt":"eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QifQ.eyJ2YyI6eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSJdLCJ0eXBlIjpbIlZlcmlmaWFibGVDcmVkZW50aWFsIl0sImNyZWRlbnRpYWxTdWJqZWN0Ijp7ImFnZSI6MjAsIm5hbWUiOiJ0ZXN0In19LCJuYmYiOjE3MjA0OTk4MzQsImlzcyI6ImRpZDpldGhyOjB4MDMwYTQ4YjJlMmM0ODkwZmYyYzI2YjkxYjkzZjhmODk5MTkxYzIxYmQ2ZDUyNzIyZTYyYTUyNTFjNTVkZmEyMmE1In0.1nRHUig219PlBaUDjWUW7h-63C1owP0Qd_epijgLaftlS-XyIafO2KHQQbBF_x2t1-nB49rW1DlhpItkV-Dmmi"}}
     */
    vcObject?: any;

    /**
     * (任意) 検証を実行するVPのJSONテキストデータ。VPのJSONテキストデータを入力して検証を実行する場合は必須。
     *
     * @type {any}
     * @memberof VerificationDto
     * @example {"credentialSubject":{"age":20,"name":"test"},"issuer":{"id":"did:ethr:0x030a48b2e2c4890ff2c26b91b93f8f899191c21bd6d52722e62a5251c55dfa22a5"},"type":["VerifiableCredential"],"@context":["https://www.w3.org/2018/credentials/v1"],"issuanceDate":"2024-07-09T04:37:14.000Z","proof":{"type":"JwtProof2020","jwt":"eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QifQ.eyJ2YyI6eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSJdLCJ0eXBlIjpbIlZlcmlmaWFibGVDcmVkZW50aWFsIl0sImNyZWRlbnRpYWxTdWJqZWN0Ijp7ImFnZSI6MjAsIm5hbWUiOiJ0ZXN0In19LCJuYmYiOjE3MjA0OTk4MzQsImlzcyI6ImRpZDpldGhyOjB4MDMwYTQ4YjJlMmM0ODkwZmYyYzI2YjkxYjkzZjhmODk5MTkxYzIxYmQ2ZDUyNzIyZTYyYTUyNTFjNTVkZmEyMmE1In0.1nRHUig219PlBaUDjWUW7h-63C1owP0Qd_epijgLaftlS-XyIafO2KHQQbBF_x2t1-nB49rW1DlhpItkV-Dmmi"}}
     */
    vpObject?: any;
}
