/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { User } from './user';
import { VcInfo } from './vc-info';
import { VpInfo } from './vp-info';
 /**
 * 
 *
 * @export
 * @interface Verification
 */
export interface Verification {

    /**
     * (必須) 検証結果の識別子
     *
     * @type {string}
     * @memberof Verification
     * @example 123e4567-e89b-12d3-a456-426614174000
     */
    id: string;

    /**
     * (必須) 検証結果の識別や整理などの管理するにあったてメタデータとして任意で設定可能な単語のフレーズ。(例: verify-for-check)
     *
     * @type {string}
     * @memberof Verification
     * @example verification-1
     */
    label: string;

    /**
     * (必須) VC/VPの検証結果(true: 検証に成功, false: 検証に失敗)
     *
     * @type {boolean}
     * @memberof Verification
     * @example true
     */
    result: boolean;

    /**
     * (任意) 検証結果を作成したユーザーアカウント
     *
     * @type {User}
     * @memberof Verification
     */
    createdBy: User;

    /**
     * (任意) 検証を実行したVC情報の識別子
     *
     * @type {VcInfo}
     * @memberof Verification
     */
    vcInfo?: VcInfo;

    /**
     * (任意) 検証を実行したVP情報の識別子
     *
     * @type {VpInfo}
     * @memberof Verification
     */
    vpInfo?: VpInfo;

    /**
     * (必須) 検証実行時の日時
     *
     * @type {string}
     * @memberof Verification
     * @example 2024-05-24T06:39:25.756Z
     */
    createdAt: string;

    /**
     * (必須) 検証結果の最終更新日
     *
     * @type {string}
     * @memberof Verification
     * @example 2024-05-24T06:39:25.756Z
     */
    updatedAt: string;
}
