/* tslint:disable */
/* eslint-disable */
/**
 * iDroit Dashboard Admin API
 *      これは[株式会社フォアー](https://www.fore-co.ltd/ja/)が開発するを使ったDecentralizd Identifiers / Verifiable Credentials(DID/VC)に関係する機能を簡単に利用するための REST API です。現在以下のユースケースをサポートしています。これは今後も拡張されていきます。     - DIDの生成:      - グループ管理機能       - (企業/プロジェクトのまとまり)ごとにユーザー、クライアント、証明書(VC)スキーマを紐付けて管理する。          詳細は以下を参照してください。     - [idroit dashboard admin UI](https://admin.idroit-dashboard.com)     - [idroit dashboard公式ホームページ]()     - [idroit dashboard操作マニュアル]()      以下は関連リンクです。     - [Universal Resolver](https://dev.uniresolver.io/)     - [W3C DID Core 1.0](https://www.w3.org/TR/did-core/)     - [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0/)   
 *
 * OpenAPI spec version: 0.9.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { LinkDto } from './link-dto';
import { MetaDto } from './meta-dto';
import { VpInfo } from './vp-info';
 /**
 * 
 *
 * @export
 * @interface VpInfoResponseDto
 */
export interface VpInfoResponseDto {

    /**
     * @type {Array<VpInfo>}
     * @memberof VpInfoResponseDto
     * @example [{"id":"dcb884cb-bf93-437d-906b-67fb893dea98","hash":"Qma1dK93xnJpyuSeQcFiq6JC5LANRTBegE3EUN79udbCcv","description":"","createdAt":"2024-07-09T04:37:14.248Z","updatedAt":"2024-07-09T04:37:14.248Z","raw":"{\"hoge\":\"a\"..."}]
     */
    items: Array<VpInfo>;

    /**
     * @type {MetaDto}
     * @memberof VpInfoResponseDto
     */
    meta: MetaDto;

    /**
     * @type {LinkDto}
     * @memberof VpInfoResponseDto
     */
    links: LinkDto;
}
